# Generated by Django 4.1.5 on 2023-01-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_alter_ledger_isactive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ledger",
            old_name="isActive",
            new_name="is_active",
        ),
    ]
