# Generated by Django 4.1.5 on 2023-01-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_rename_isactive_ledger_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledger",
            options={"verbose_name": "가계부"},
        ),
    ]
