# Generated by Django 4.1.5 on 2023-01-17 10:31

from django.db import migrations
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.managers.UserManager()),
            ],
        ),
    ]
